[package]
name = "nano_image_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7.9"

# This will be replaced once the WASM bindgen Version requirement issue is fixed in photon rs
photon-rs = { version = "0.3.2" ,git = "https://github.com/silvia-odwyer/photon", rev = "3b72d357848cd76be9363e87ad0cd02a19b988d2"}
tower-http = { version = "0.6.2", features = ["fs"]}
serde = "1.0.216"
image = "0.25.5"

