[package]
name = "nano_image_server"
version = "0.7.0-beta"
edition = "2024"

[dependencies]
tokio = { version = "1.52.3", features = ["rt-multi-thread","fs","signal"] }
axum = "0.8.9"
serde = { version = "1.0.216", features = ["derive"] }
thiserror = "2.0.17"
tracing-subscriber = { version = "0.3.23",  features = ["env-filter","fmt"]}
tracing = "0.1.44"

[features]
default = []
all = ["cache"]

cache = []

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
