[package]
name = "nano_image_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7.9"
tower-http = { version = "0.6.2", features = ["fs"]}
serde = { version = "1.0.216", features = ["derive"] }
image = "0.25.5"

