name: Linux Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build Minimal
      run: cargo build --verbose --release 
    - name: Build with Cache Feature Only
      run: cargo build --verbose --release --features cache
    - name: Build with TLS Feature Only
      run: cargo build --verbose --release --features tls
    - name: Build with full features
      run: cargo build --verbose --release --features all  

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Run tests
      run: cargo test --verbose --features all  
